[package]
name = "DomTestingLibrary"
version = "8.16.1"
authors = [
    "Ignacio Falk <flakolefluk@gmail.com>",
    "Allan Jeremy <dev@allanjeremy.com>",
    "Paul Doyle <pdoyle@roblox.com>",
]
content_root = "src"
files = ["*", "!**/__tests__/**", "!**/.robloxrc"]

[config]
registry_index = true

[dependencies]
LuauPolyfill = {version = "1.0.0", package = "LuauPolyfill" }
LuauRegExp = { version = "0.3.0", package = "RegExp" }
Chalk = { target = "github.com/roblox/chalk-lua", version = "0.3.0", package = "ChalkLua" }
Promise = { version = "3.3.0", package = "Promise" }
JestGetType = { version = "3.10.0", package = "JestGetType" }
PrettyFormat = { version = "3.10.0", package = "PrettyFormat" }
RobloxShared = { version = "3.10.0", package = "RobloxShared" }
JestGlobals = { version = "3.10.0", package = "JestGlobals" }

[dev_dependencies]
Jest = { version = "3.10.0", package = "Jest" }
